name = "TeawieSMP Modpack"
author = "hisashiburi & getchoo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5905f53c3e5246864c8d173d9284c99b7ff040d94fe3a32c948382cf4a681b60"

[versions]
fabric = "0.14.19"
minecraft = "1.19.3"
