name: Update mods

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-mods:

    runs-on: ubuntu-latest

    steps:
      - name: get packwiz
        run: |
          curl -fsSLo ~/packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip -d ~ ~/packwiz.zip
          chmod 755 ~/packwiz

      - uses: actions/checkout@v3.3.0

      - name: update mods
        run: |
          echo "y" | ~/packwiz update --all

      - name: commit updates
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update mods"
